### PR TITLE
remove socket listeners on “abort”

### LINKED ISSUE #4993: Remix crashes with web-fetch 4.3.2/1.8.2
### What version of Remix are you using?

1.8.2

### Steps to Reproduce

See sandbox: https://codesandbox.io/p/sandbox/solitary-wave-1l0skr
Failing test PR: https://github.com/remix-run/remix/pull/4994

1. Observe exit code 1 (remix crashes, premature close error) when fetcher loads from /load.tsx route, which calls fetch from a Google drive URL
2. Go to load.tsx, uncomment the import that uses web-fetch 4.3.1
3. Remix no longer crashes

### Expected Behavior

web-fetch's fetch should work, without crashing remix, returning a valid HTML result

### Actual Behavior

remix crashes, exit code 1

```
/project/sandbox/node_modules/@remix-run/node/node_modules/@remix-run/web-fetch/src/fetch.js:342
                                const error = Object.assign(new Error('Premature close'), {
                                ^
Error: Premature close
    at TLSSocket.onSocketClose (/project/sandbox/node_modules/@remix-run/node/node_modules/@remix-run/web-fetch/src/fetch.js:342:33)
    at TLSSocket.emit (node:events:525:35)
    at node:net:757:14
    at TCP.done (node:_tls_wrap:584:7)
error Command failed with exit code 1.
```

### Related issues:

https://github.com/remix-run/remix/issues/4737

### PR DESCRIPTION
**Pull request by donavon**
this was done in 4.3.1, but was removed on 4.3.2, so put it back

fixes https://github.com/remix-run/remix/issues/4993

### CODE REVIEW

**Review by jdnichollsc — APPROVED** [review]
LGTM!

**Comment by dwene** [comment]
Hey y'all, we're having this problem too and would love to get this fix merged!

**Comment by donavon-silverback** [comment]
bueller-ben-stein

**Review by MichaelDeBoey — APPROVED** [review]

**Comment by jeeyoungk** [comment]
Is there a plan to merge / publish this? I believe that this is causing breakage with websites with redirects.

**Comment by MichaelDeBoey** [comment]
CC/ @brophdawg11 @jacob-ebey

**Pull request merged**
